The change in commit c2974b1376716f6f521baab530c9c08355540c5b to file src/frontend/coalesce.ml on line 40:
-   List.combine (int_compr [] n) args
+   List.mapi (fun i x -> (n - i, x))

breaks compatibility with Ocaml 4.06.1:

```bash
markus@avocado:~/src/TLA/tlapm/tlaps-1.4.5-x86_64-linux-gnu/build/tlapm((HEAD detached at c2974b1))$ make all install
rm -f tlapm
make -C src tlapm.native
make[1]: Entering directory '/home/markus/src/TLA/tlapm/tlaps-1.4.5-x86_64-linux-gnu/build/tlapm/src'
cd `dirname frontend/coalesce.ml` \
&& ocamlopt -annot -g -warn-error +1+2+5+6+8+10..26+29..31+36 -unsafe-string  -I . -I backend -I frontend -I expr -I module -I proof -I util -I pars -I typesystem -I smt -I ../backend -I ../frontend -I ../expr -I ../module -I ../proof -I ../util -I ../pars -I ../typesystem -I ../smt -I .. -c `basename frontend/coalesce.ml`
File "coalesce.ml", line 76, characters 25-44:
76 |         List.map map_fun (indexed_args args) in
                              ^^^^^^^^^^^^^^^^^^^
Error: This expression has type 'weak5 list -> (int * 'weak5) list
       but an expression was expected of type
         (int * Expr.T.expr_ Property.wrapped) list
make[1]: *** [Makefile:140: frontend/coalesce.cmx] Error 2
make[1]: Leaving directory '/home/markus/src/TLA/tlapm/tlaps-1.4.5-x86_64-linux-gnu/build/tlapm/src'
make: *** [Makefile:30: tlapm] Error 2
```

However, Ocaml `4.06.1` used to be the version used by the
[Github Actions](https://github.com/tlaplus/tlapm/tree/master/.github/workflows).

This commit, thus, bumps Ocaml in the Github Actions to `4.08.1`.

[Build]