BUG: rm quotes (`'`) from around env-var values
because GitHub Actions inserts the quotes in
the values of the environment variables that
are created from the assignments that are
printed by the script `setup_shell_env.py`.

For example, the line in the file `release.yml`:

```yaml
asset_path: tools/installer/${{ env.INSTALLER }}
```

results, when interpreted by GitHub Actions,
in the value:

```
asset_path: tools/installer/'tlaps-1.5.0-x86_64-linux-gnu-inst.bin'
```

which raises in CI the error:

```
Error: ENOENT: no such file or directory, stat 'tools/installer/'tlaps-1.5.0-x86_64-linux-gnu-inst.bin''
```